PopCornOneWebApp/Controllers/AutorController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PopCornOneWebApp.Models;

namespace PopCornOneWebApp.Controllers
{   
    public class AutorController : Controller
    {
        public ActionResult AutorWidget()
        {
            return View();
        }
    }
}

PopCornOneWebApp/Controllers/LanguageController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PopCornOneWebApp.Models;

namespace PopCornOneWebApp.Controllers
{   
    public class LanguageController : Controller
    {
        public ActionResult LanguageWidget()
        {
            return View();
        }
    }
}

PopCornOneWebApp/Controllers/OriginController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PopCornOneWebApp.Models;

namespace PopCornOneWebApp.Controllers
{   
    public class OriginController : Controller
    {
        public ActionResult OriginWidget()
        {
            return View();
        }
    }
}

PopCornOneWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-1.7.min.js")" type="text/javascript"></script>
</head>
<body>
    <div class="page">
        <header>
            <div id="title">
                <h1>My MVC Application</h1>
            </div>
            <div id="logindisplay">
                @Html.Partial("_LogOnPartial")
            </div>
            <nav>
                <ul id="menu">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                </ul>
            </nav>
        </header>
        <section id="main">
            @RenderBody()
        </section>
        <footer>
        </footer>
    </div>
</body>
</html>

PopCornOneWebApp/Views/Shared/_LayoutModular.cshtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title>@ViewBag.Title</title>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
    <meta name="author" content="The Man in Blue" />
    <meta name="robots" content="all" />
    <meta name="MSSmartTagsPreventParsing" content="true" />
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <link href="@Url.Content("~/Content/themes/modular/main.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/themes/metroUI/metro.blue.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/themes/datatable/jquery.dataTables_themeroller.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/themes/base/jquery.ui.all.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/themes/base/jquery.ui.core.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/themes/base/jquery.ui.base.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/themes/base/jquery-ui-1.8.21.custom.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/modular/event_listeners.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modular/class_names.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modular/expand_collapse.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modular/modular.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.dataTables.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-1.7.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.8.21.custom.min.js")" type="text/javascript"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#phrasesTable').dataTable({
                "bJQueryUI": true,
                "sPaginationType": "full_numbers"
            }
            );
        });
    </script>
    <script type="text/javascript" src="../../Scripts/Silverlight.js"></script>
    <script type="text/javascript">
        function onSilverlightError(sender, args) {
            var appSource = "";
            if (sender != null && sender != 0) {
                appSource = sender.getHost().Source;
            }

            var errorType = args.ErrorType;
            var iErrorCode = args.ErrorCode;

            if (errorType == "ImageError" || errorType == "MediaError") {
                return;
            }

            var errMsg = "Unhandled Error in Silverlight Application " + appSource + "\n";

            errMsg += "Code: " + iErrorCode + "    \n";
            errMsg += "Category: " + errorType + "       \n";
            errMsg += "Message: " + args.ErrorMessage + "     \n";

            if (errorType == "ParserError") {
                errMsg += "File: " + args.xamlFile + "     \n";
                errMsg += "Line: " + args.lineNumber + "     \n";
                errMsg += "Position: " + args.charPosition + "     \n";
            }
            else if (errorType == "RuntimeError") {
                if (args.lineNumber != 0) {
                    errMsg += "Line: " + args.lineNumber + "     \n";
                    errMsg += "Position: " + args.charPosition + "     \n";
                }
                errMsg += "MethodName: " + args.methodName + "     \n";
            }

            throw new Error(errMsg);
        }
    </script>
</head>
<body>
    <div id="header">
        <h1>
            <span class="replacement"></span>
            <a href="#">
                <span class="replacement"></span>
                Pop Corn One Manager
            </a>
        </h1>
    </div>
    <!-- END #header -->
    <div id="content">
        <div id="modules1">
            <div id="moduleSearch" class="module">
                <h3 class="moduleheader">
                    Languages
                </h3>
                <div class="moduleContent">
                    @{Html.RenderAction("LanguageWidget", "Language");}
                </div>
                <!-- END .moduleContent -->
            </div>
            <!-- END .module -->
            <div id="moduleOrigin" class="module">
                <h3 class="moduleheader">
                    Origins
                </h3>
                <div class="moduleContent">
                    @{Html.RenderAction("OriginWidget", "Origin");}
                </div>
                <!-- END .moduleContent -->
            </div>
            <!-- END .module -->
        </div>
        <!-- END #modules1 -->
        <div id="news" class="module">
            <div class="moduleInner">
                <h2 class="moduleheader">
                    Phrase Editor
                </h2>
                <div class="moduleContent">
                    @RenderBody()
                    <div class="clearer">
                    </div>
                </div>
                <!-- END .moduleContent -->
            </div>
            <!-- END .moduleInner -->
            <div class="moduleInner">
                <h3 class="moduleheader">
                    Autor Editor
                </h3>
                <div class="moduleContent">
                        @{Html.RenderAction("AutorWidget", "Autor");}
                    <div class="clearer">
                    </div>
                </div>
                <!-- END .moduleContent -->
            </div>
            <!-- END .moduleInner -->
        </div>
        <!-- END .module -->
        <div id="modules2">
            <!-- Add Widget at right column -->
        </div>
        <!-- END #modules2 -->
        <div class="clearer">
        </div>
    </div>
    <!-- END #content -->
</body>
</html>

PopCornOneWebApp/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Welcome <strong>@User.Identity.Name</strong>!
    [ @Html.ActionLink("Log Off", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "LogOn", "Account") ]
}